version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install --production=false
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules
artifacts:
  files:
    - 'package*.json'
    - 'public/**/*'
    - 'src/app.modules/graphql/*'
    - '.next/**/*'
    - '.ebextensions/**/*'
    - '.npmrc'
cache:
  paths:
    - 'node_modules/**/*'
